// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFooi_xVSLa9AWbzIU_hEYuY7iogaa3k',
    appId: '1:928209446112:web:74dc0fc34ace502abd5c85',
    messagingSenderId: '928209446112',
    projectId: 'style-scout-4f39d',
    authDomain: 'style-scout-4f39d.firebaseapp.com',
    storageBucket: 'style-scout-4f39d.firebasestorage.app',
    measurementId: 'G-HNM84S2YSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByflnBrez2VW4QBqDr3x_0w2Pve0zpBZU',
    appId: '1:928209446112:android:5a1dd7b78ea13cc2bd5c85',
    messagingSenderId: '928209446112',
    projectId: 'style-scout-4f39d',
    storageBucket: 'style-scout-4f39d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmqPn5tZzrPyhV2fuKi3eM74gPdrqNjsQ',
    appId: '1:928209446112:ios:1a2915f2c1c81bd9bd5c85',
    messagingSenderId: '928209446112',
    projectId: 'style-scout-4f39d',
    storageBucket: 'style-scout-4f39d.firebasestorage.app',
    iosBundleId: 'com.example.styleScout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmqPn5tZzrPyhV2fuKi3eM74gPdrqNjsQ',
    appId: '1:928209446112:ios:1a2915f2c1c81bd9bd5c85',
    messagingSenderId: '928209446112',
    projectId: 'style-scout-4f39d',
    storageBucket: 'style-scout-4f39d.firebasestorage.app',
    iosBundleId: 'com.example.styleScout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcFooi_xVSLa9AWbzIU_hEYuY7iogaa3k',
    appId: '1:928209446112:web:7b56c3ff68ce44d2bd5c85',
    messagingSenderId: '928209446112',
    projectId: 'style-scout-4f39d',
    authDomain: 'style-scout-4f39d.firebaseapp.com',
    storageBucket: 'style-scout-4f39d.firebasestorage.app',
    measurementId: 'G-Q09XV9ECRE',
  );
}
